name: CD — Deploy to K8s

on:
  push:
    branches: [main]

env:
  DOCKERHUB_USERNAME: artisingh3106
  DOCKER_HOST: npipe:////./pipe/docker_engine

jobs:
  deploy:
    name: Build, Push & Deploy
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: docker login -u ${{ env.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build backend image
        run: docker build -t ${{ env.DOCKERHUB_USERNAME }}/healthcare-backend:latest -t ${{ env.DOCKERHUB_USERNAME }}/healthcare-backend:${{ github.sha }} ./backend

      - name: Push backend image
        run: |
          docker push ${{ env.DOCKERHUB_USERNAME }}/healthcare-backend:latest
          docker push ${{ env.DOCKERHUB_USERNAME }}/healthcare-backend:${{ github.sha }}

      - name: Build frontend image
        run: docker build -f Dockerfile.frontend -t ${{ env.DOCKERHUB_USERNAME }}/healthcare-frontend:latest -t ${{ env.DOCKERHUB_USERNAME }}/healthcare-frontend:${{ github.sha }} .

      - name: Push frontend image
        run: |
          docker push ${{ env.DOCKERHUB_USERNAME }}/healthcare-frontend:latest
          docker push ${{ env.DOCKERHUB_USERNAME }}/healthcare-frontend:${{ github.sha }}

      - name: Deploy to K8s
        run: |
          kubectl set image deployment/backend backend=${{ env.DOCKERHUB_USERNAME }}/healthcare-backend:${{ github.sha }} -n healthcare
          kubectl set image deployment/frontend frontend=${{ env.DOCKERHUB_USERNAME }}/healthcare-frontend:${{ github.sha }} -n healthcare
          kubectl rollout status deployment/backend -n healthcare --timeout=120s
          kubectl rollout status deployment/frontend -n healthcare --timeout=120s

      - name: Verify deployment
        run: kubectl get pods -n healthcare
